apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-bgp-vip
  labels:
    k8s-app: kube-bgp-vip
spec:
  replicas: 1
  selector:
    k8s-app: kube-bgp-vip
  template:
    metadata:
      labels:
        k8s-app: kube-bgp-vip
        name: kube-bgp-vip
    spec:
      hostNetwork: true
      containers:
      - image: aledbf/kube-bgp-vip:0.1
        name: kube-bgp-vip
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
      volumes:
      - hostPath:
          path: /lib/modules
        name: modules
